services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: smart-support-pgvector

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Barsa@123
      POSTGRES_DB: smart-support-assistant

    ports:
      - "5433:5432"

    volumes:
      - pgvector_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend

    container_name: smart-support-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build:
      context: ./frontend

    container_name: smart-support-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    volumes:
      - ./frontend:/app
      - /app/node_modules

    command: npm run dev -- --host


volumes:
  pgvector_data: